version: '3.4'

services:
  svsttest02:
    image: ${DOCKER_REGISTRY-}svsttest02
    build:
      context: .
      dockerfile: SVSTTest02/Dockerfile

  svsttest002client:
    image: ${DOCKER_REGISTRY-}svsttest002client
    build:
      context: .
      dockerfile: SVSTTest002Client/Dockerfile

