version: '3.4'
name: svsttest002
networks:
  svsttest002network:
    driver: bridge

services:
  svsttest02:
    container_name: svsttest02
    image: ${DOCKER_REGISTRY-}svsttest02
    build:
      context: .
      dockerfile: SVSTTest02/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "801:80"
      - "4431:443"
    networks:
      - svsttest002network
    depends_on:
      - svsttest002postgres
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  svsttest002client:
    container_name: svsttest002client
    image: ${DOCKER_REGISTRY-}svsttest002client
    build:
      context: .
      dockerfile: SVSTTest002Client/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "802:80"
      - "4432:443"
    networks:
      - svsttest002network
    depends_on:
      - svsttest02
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  svsttest002postgres:
    container_name: svsttest002postgres
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass112233word
      POSTGRES_DB: stal
    ports:
      - "5433:5432"
    networks:
      - svsttest002network
    volumes:
      - svsttest002postgresvolume:/var/lib/postgresql/data

volumes:
  svsttest002postgresvolume:
