version: '3.4'
name: svsttest002
networks:
  svsttest002network:
    driver: bridge


services:
  svsttest02:
    image: ${DOCKER_REGISTRY-}svsttest02
    build:
      context: .
      dockerfile: SVSTTest02/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "801:80"
      - "4431:443"
    networks:
      - svsttest002network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  svsttest002client:
    image: ${DOCKER_REGISTRY-}svsttest002client
    build:
      context: .
      dockerfile: SVSTTest002Client/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "802:80"
      - "4432:443"
    networks:
      - svsttest002network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  svsttest002postgres:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass112233word
      POSTGRES_DB: svsttest002postgresdb
    ports:
      - "5433:5432"
    networks:
      - svsttest002network
    volumes:
      - svsttest002postgresvolume:/var/lib/postgresql/data

volumes:
  svsttest002postgresvolume:


